server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的服务名称
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource  #?????????
#    driver-class-name: org.gjt.mm.mysql.Driver  #??????
#    url: jdbc:mysql://localhost:3306/svms?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#    username: root
#    password: password
  cloud:
    config:
      server:
        git:
          skipSslValidation: true # 跳过ssl认证
          uri: https://github.com/lixiangyun-Dev/springcloud-config.git  #GitHub上复制的项目地址
          search-paths:  #搜索目录
            - springcloud-config
      label: master
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

