
server:
  port: 8001
#spring配置
spring:
  application:
    name: mcroservice-payment  #服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/svms?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: password
    druid:
      test-while-idle: false
#mybatis:??
mybatis:
  mapperLocations: classpath:dao/*.xml
  type-aliases-package: com.lxy.cloudapicommons.entity

