server:
  port: 80

spring:
  application:
    name: mcroservice-feign-order  #???
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #?????????
    driver-class-name: org.gjt.mm.mysql.Driver  #??????
    url: jdbc:mysql://localhost:3306/svms?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: password

#eureka??
eureka:
  client:
    #??????????eureka  ???true
    register-with-eureka: false
    #???EurekaServer??????????????true?????????????true???ribbon??????
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #??????
    instance-id: feign-order
    #????????ip??
    prefer-ip-address: true

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间，设置等待5000为5秒时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.lxy.cloudconsumerfeignorder.service.PaymentService: debug