
server:
  port: 8003
#spring??
spring:
  application:
    name: mcroservice-payment  #???
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/svms?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: password
    druid:
      test-while-idle: false
#mybatis:??
mybatis:
  mapperLocations: classpath:dao/*.xml
  type-aliases-package: com.lxy.cloudapicommons.entity

#eureka??
eureka:
  client:
    #??????????eureka  ???true
    register-with-eureka: true
    #???EurekaServer??????????????true?????????????true???ribbon??????
    fetch-registry: true
    service-url:
      #????
      #      defaultZone: https://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #??????
    instance-id: payment-8003
    #????????ip??
    prefer-ip-address: true

