server:
  port: 80

spring:
  application:
    name: mcroservice-feign-hystrix-order  #???
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #?????????
    driver-class-name: org.gjt.mm.mysql.Driver  #??????
    url: jdbc:mysql://localhost:3306/svms?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: password

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #??????
    instance-id: feign-hystrix-order
    #????????ip??
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true