
server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #?????????
    driver-class-name: org.gjt.mm.mysql.Driver  #??????
    url: jdbc:mysql://localhost:3306/svms?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: password
  cloud:
    consul:
      # consul??????
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}

